- task: KubernetesManifest@0
  displayName: Create imagePullSecret
  inputs:
    action: createSecret
    secretName: acr-secret
    dockerRegistryEndpoint: da709a97-5e40-45fe-9929-b2cd834d5ad4
    kubernetesServiceConnection: 'aks-cluster-default'

- task: KubernetesManifest@0
  displayName: DeployAuthService
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-cluster-default'
    manifests: 'k8s/api1-deployment.yaml'
    containers: 'api1-container'
    imagePullSecrets: 'acr-secret'

- task: KubernetesManifest@0
  displayName: DeployProductService
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'aks-cluster-default'
    manifests: 'k8s/api2-deployment.yaml'
    containers: 'api2-container'
    imagePullSecrets: 'acr-secret'
