apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: ingress-basic
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: amcart-api.centralindia.cloudapp.azure.com 
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: amcartauthapi-service
                port:
                  number: 80
          - path: /products
            pathType: Prefix
            backend:
              service:
                name: amcartproductapi-service
                port:
                  number: 80
