apiVersion : apps/v1
kind: Deployment
metadata:
  name: amcartproductapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amcartproductapi
  template:
    metadata:
      labels:
        app: amcartproductapi 
    spec:
      containers:
        - name: amcartproductapi 
          image: amcartapireg.azurecr.io/amcartproductapi
          ports:
          - containerPort: 80