apiVersion: v1
kind: Service
metadata:
    name: amcartproductapi-service-lb
    namespace: ingress-basic
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 80
    selector:
        app: amcartproductapi