apiVersion: v1
kind: Service
metadata:
    name: amcartproductapi-service-lb
    namespace: ingress-basic
spec:
    type: LoadBalancer
    ports:
    - port: 80 
      targetPort: 8080
    selector:
        app: amcartproductapi