apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: ingress-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth-container
        image: crnagp.azurecr.io/nagp-auth-api-repo:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ingress-basic
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP
