apiVersion: v1
kind: Service
metadata:
  name: product-service-lb
  namespace: ingress-basic
  labels:
    app: product-lb
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: product
