apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-annotation: "trigger-change"
  name: product-deployment
  namespace: ingress-basic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-container
        image: productapi.azurecr.io/product:1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
# apiVersion: v1
# kind: Service
# metadata:
  # name: product-service
  # namespace: ingress-basic
# spec:
  # selector:
    # app: product
  # ports:
    # - protocol: TCP
      # port: 80
      # targetPort: 80
  # type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: product-service-lb
  namespace: ingress-basic
  labels:
    app: product-lb
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: product
